-- Database schema for Omni-Tracker
-- Run this SQL against your Supabase/PostgreSQL instance.

-- ============================================================
-- Privacy model (Telegram-only identity)
-- ============================================================
-- We key all rows by telegram_user_id (bigint).
-- The Streamlit dashboard is accessed via a signed magic link generated by the bot.
-- No Supabase Auth / RLS required for end users.

create table if not exists expenses (
    id bigserial primary key,
    created_at timestamptz not null default now(),
    telegram_user_id bigint not null,
    date date not null default current_date,
    amount numeric(14, 2) not null check (amount >= 0),
    currency text not null,
    category text not null,
    description text,
    split_with text[] not null default '{}'
);

create index if not exists idx_expenses_date on expenses (date);
create index if not exists idx_expenses_telegram_date on expenses (telegram_user_id, date);

create table if not exists fitness (
    id bigserial primary key,
    created_at timestamptz not null default now(),
    telegram_user_id bigint not null,
    date date not null default current_date,
    activity_type text not null,
    duration_minutes integer not null check (duration_minutes >= 0)
);

create index if not exists idx_fitness_date on fitness (date);
create index if not exists idx_fitness_telegram_date on fitness (telegram_user_id, date);

create table if not exists nutrition (
    id bigserial primary key,
    created_at timestamptz not null default now(),
    telegram_user_id bigint not null,
    date date not null default current_date,
    food_item text not null,
    calories integer not null check (calories >= 0)
);

create index if not exists idx_nutrition_date on nutrition (date);
create index if not exists idx_nutrition_telegram_date on nutrition (telegram_user_id, date);

-- Note:
-- If you previously enabled RLS / created user_id columns, migrate manually:
-- - add telegram_user_id columns
-- - backfill values if possible
-- - drop RLS policies and user_links table

